name: Greeting from Sabhari
on: [push, pull_request]
jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '10.10'
    - name: Print a greeting
      run: |
        gem install bundler -v 1.17.2
        bundle install
        bundle exec rspec
        rubocop --out result.txt
        echo "sabhari karthik"
      env: 
        BUNDLE_GEMFILE: Gemfile
