name: Test CI CD
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install postgres
      run: |
        ./setup_postgres.sh -u ${{ secrets.DB_USERNAME }} -p ${{ secrets.DB_PASSWORD }}
    - name: Install bundler
      run: |
        gem install bundler -v 1.17.2
    - name: Install gems and migrate the database
      run: |
        bundle install
        rake db:create db:migrate
      env:
         RAILS_ENV: test
         DB_USERNAME: ${{ secrets.DB_USERNAME }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         DB_HOST: ${{ secrets.DB_HOST }}
         DB_PORT: ${{ secrets.DB_PORT }}
    - name: Execute test cases and check the code coverage
      run: |
        bundle exec rspec
        echo "success"
      env:
         RAILS_ENV: test
         
