name: Greeting from Sabhari
on: [push, pull_request]
jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: sabhari
          POSTGRES_PASSWORD: Sabari123
          POSTGRES_DB: test_CI_CD_development
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Print a greeting
      run: |
        gem install bundler -v 1.17.2
        bundle install
        bundle exec rspec
        rubocop --out result.txt
        echo "sabhari karthik"
      env: 
        BUNDLE_GEMFILE: Gemfile
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} 
