name: Greeting from Sabhari
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Execute test cases and check the code coverage
      run: |
        sudo apt-get install wget ca-certificates
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
        sudo apt-get update
        sudo apt-get install postgresql postgresql-contrib
        sudo apt-get install libpq-dev
        sudo -u postgres bash -c "psql -c \"CREATE ROLE ${{ secrets.DB_USERNAME }} WITH PASSWORD '${{ secrets.DB_PASSWORD }}' LOGIN SUPERUSER;\""
        gem install bundler -v 1.17.2
        bundle install
        rake db:create db:migrate
        bundle exec rspec
        echo "success"
      env:
         RAILS_ENV: test
         DB_USERNAME: ${{ secrets.DB_USERNAME }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         DB_HOST: ${{ secrets.DB_HOST }} 
         DB_PORT: ${{ secrets.DB_PORT }}
