name: Greeting from Sabhari
on: [push, pull_request]
jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        sudo apt-get install ruby-full
        sudo gem install bundler -v 1.17.3
        ls
        bundle install --gemfile Gemfile
        bundle exec rspec
        rubocop --out result.txt
        echo "sabhari karthik"
