name: Greeting from Sabhari
on: [push, pull_request]
jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Print a greeting
      run: |
        sudo apt-get install ruby-2.6.3
        sudo gem install bundler -v 1.17.2
        bundle install
        bundle exec rspec
        rubocop --out result.txt
        echo "sabhari karthik"
      env: 
        BUNDLE_GEMFILE: Gemfile
