name: Greeting from Sabhari
on: [push, pull_request]
jobs:
  build:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        bundle install
        bundle exec rspec
        rubocop --out result.txt
        echo "sabhari karthik"
